swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /api
paths:
  /daily_poetry/:
    get:
      tags:
      - daily_poetry
      description: get all Interests
      operationId: PoetryController.GetDailyPoetry
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.DailyPoetry'
  /interests/:
    get:
      tags:
      - interests
      description: get all Interests
      operationId: InterestController.GetAll
      parameters:
      - in: query
        name: page
        description: page
        type: integer
        default: "1"
      - in: query
        name: ipp
        description: ipp
        type: integer
        default: "10"
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.InterestList'
  /user/interests/:
    post:
      tags:
      - user/interests
      description: get all Interests
      operationId: UserInterestController.CreateUserInterest
      parameters:
      - in: body
        name: body
        description: "true"
        schema:
          $ref: '#/definitions/models.UserInterestReq'
      responses:
        "200":
          description: '{}'
definitions:
  models.DailyPoetry:
    title: DailyPoetry
    type: object
    properties:
      poetry:
        $ref: '#/definitions/models.JsonPoetry'
      today_date:
        type: string
      week:
        type: integer
        format: int64
  models.Interest:
    title: Interest
    type: object
    properties:
      id:
        type: integer
        format: int64
      text:
        type: string
  models.InterestList:
    title: InterestList
    type: object
    properties:
      ipp:
        type: integer
        format: int64
      objects:
        type: array
        items:
          $ref: '#/definitions/models.Interest'
      page:
        type: integer
        format: int64
      total:
        type: integer
        format: int64
  models.JsonPoetry:
    title: JsonPoetry
    type: object
    properties:
      ananlysis:
        type: string
      author:
        type: string
      author_tr:
        type: string
      background:
        type: string
      content:
        type: array
        items:
          type: string
      content_tr:
        type: array
        items:
          type: string
      id:
        type: integer
        format: int64
      idx:
        type: integer
        format: int64
      title:
        type: string
      title_tr:
        type: string
  models.UserInterestReq:
    title: UserInterestReq
    type: object
    properties:
      interest_ids:
        type: array
        items:
          type: integer
          format: int64
tags:
- name: interests
  description: |
    Operations about Interest
- name: daily_poetry
  description: |
    Operations about Poetry
